import type { Metadata } from "next";
// style
import "./globals.css";
import { ubuntu } from "@lib/font";
import { cn } from "@lib/utils";
// theme
import { ThemeProvider } from "@components/theme/ThemeProvider";
import Footer from "@components/footer/Footer";
import { Toaster } from "@components/ui/toaster";
import Header from "@components/header/Header";
import ProgressProvider from "@components/utility/ProgressProvider";

export const metadata: Metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(ubuntu.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <ProgressProvider>{children}</ProgressProvider>
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
