import type { Metadata } from "next";
import { Inter } from "next/font/google";
// style
import "./globals.css";
import { ubuntu } from "@/lib/font";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(ubuntu.variable)}>{children}</body>
    </html>
  );
}
