import type { Metadata, Viewport } from "next";
// style
import "./globals.css";
import { ubuntu } from "@lib/font";
import { cn } from "@lib/utils";
// theme
import { ThemeProvider } from "@components/theme/ThemeProvider";
import Footer from "@components/footer/Footer";
import { Toaster } from "@components/ui/toaster";
import Header from "@components/header/Header";
import ProgressProvider from "@components/utility/ProgressProvider";

export const metadata: Metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["online-shop"],
  authors: [
    { name: "ali seyedi" },
    {
      name: "ali seyedi",
      url: "https://www.linkedin.com/in/aliseyedi01/",
    },
  ],
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(ubuntu.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <ProgressProvider>{children}</ProgressProvider>
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
